name: Deploy to Firebase Hosting

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Verify project files
        run: |
          echo "项目文件列表:"
          ls -la
          echo "检查 index.html 是否存在:"
          if [ -f "index.html" ]; then
            echo "index.html 存在"
          elif [ -f "public/index.html" ]; then
            echo "public/index.html 存在"
          else
            echo "index.html 不存在!" >&2
            exit 1
          fi
        
      # 修改 Node.js 设置步骤，禁用缓存检查
      - name: Set up Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'npm'  # 保留缓存设置但忽略警告
          cache-dependency-path: ''  # 添加这一行禁用依赖路径检查
        
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
        
      # 添加版本检查步骤（可选）
      - name: Display versions
        run: |
          echo "Node.js version: $(node --version)"
          echo "npm version: $(npm --version)"
          echo "Firebase CLI version: $(firebase --version)"
        
      - name: Deploy to Firebase
        run: firebase deploy --project=imafeedback --only hosting --token=${{ secrets.FIREBASE_TOKEN }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}